### PR TITLE
Fix blur pdf increasing scale

### PR DESCRIPTION
**Pull request by axlEscalada**
- Increase scale by 3
- use antialiased for smoothness
Blurred rendering:
blurred

Fixed:
not-blurred

Fix this: https://github.com/johnfactotum/foliate/issues/1129

### CODE REVIEW

**Comment by johnfactotum** [comment]
It's already scaled up quite a bit in #23. I don't think it needs more fixes of this kind. And 3x is quite excessive and will slow down the rendering a lot. The proper way to fix this is to make it rerender with the correct scaling.

As for changing the text rendering, I don't think it'd have any effect as there isn't any text apart from the invisible text layer. All visible text is rendered by PDF.js on a canvas.

**Comment by Joseph-DiGiovanni** [comment]
Respectfully, I rather have slower rendering than completely unusable PDF "support"

**Comment by johnfactotum** [comment]
Yes, that's why the "support" is advertised as "experimental". In fact I [described](https://github.com/johnfactotum/foliate/issues/139#issuecomment-1752037262) it as "'fairly terrible', as in highly bugged and experimental." It's something that's provided on a "better than nothing" basis. Maybe that was a mistake but here we are.

Anyway, what it needs is, as I said, a proper fix, and not simply increasing the scale.

**Comment by Joseph-DiGiovanni** [comment]
> "support" is advertised as "experimental"

Advertised where besides this feature request comment? The README, FAQ, and troubleshooting docs make zero mention of PDF outside of the PDF.js library being used. The verified Flathub package description states "Open EPUB ... and PDF files".

Implementing a hacky solution to get it working isn't necessarily a mistake, but rejecting an equally hacky solution that makes it actually usable certainly is.

**Comment by johnfactotum** [comment]
As mentioned above, there already is a hacky solution like this one, #23, that was merged.

If you're using Foliate, though, that fix is not released yet.

**Comment by Joseph-DiGiovanni** [comment]
In that case I understand your perspective now, I don't mean to be confrontational. Just know my frustration comes from Foliate being a fantastic app with an unfortunate fatal flaw for me. I hope to see an update (and eventual proper fix) soon.

**Comment by johnfactotum** [comment]
> Advertised where besides this feature request comment? The README, FAQ, and troubleshooting docs make zero mention of PDF outside of the PDF.js library being used. The verified Flathub package description states "Open EPUB ... and PDF files".

Fair enough. But it was advertised as such in v3.0.0's release notes: https://github.com/johnfactotum/foliate/releases/tag/3.0.0.

Also, Foliate does not programmatically advertise support for PDF at all, not in the .desktop entry, and neither in the file chooser dialog.

The proper fix is probably not even that difficult to do if all you care about is the scaling (there are like a dozen other issues with PDFs, and fixed layout books in general). At present, it's not even using the latest PDF.js. The migration is probably more difficult than fixing the scaling problem given the lack of documentation.

**Comment by johnfactotum** [comment]
Fixed with 1e952102bd1932c1b9e5ddb88b5b8f41a0190a68.

**Pull request closed without merging**
